/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

self.skipWaiting();
clientsClaim();

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Events
self.addEventListener('push', (event) => {
    let data: any = { title: 'Nova Notificação', body: 'Você tem uma nova atualização!' };

    if (event.data) {
        try {
            data = event.data.json();
        } catch (e) {
            data.body = event.data.text();
        }
    }

    const options = {
        body: data.body,
        icon: '/pwa-icon.svg',
        badge: '/pwa-icon.svg',
        vibrate: [200, 100, 200, 100, 200, 100, 200],
        data: {
            url: data.url || '/'
        },
        requireInteraction: true // Keeps the notification open until the user interacts with it
    };

    event.waitUntil(
        self.registration.showNotification(data.title || 'FoodSystem', options)
    );
});

// Handle Notification Clicks
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    // Default to the origin if no specific URL was provided
    const path = event.notification.data?.url || '/';
    const urlToOpen = new URL(path, self.location.origin).href;

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            for (let i = 0; i < windowClients.length; i++) {
                const windowClient = windowClients[i];
                if (windowClient.url === urlToOpen && 'focus' in windowClient) {
                    return windowClient.focus();
                }
            }

            // If no window/tab was found open the target URL
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen);
            }
        })
    );
});
